version: 3

vars:
  COMPILER: 'gcc'
  TYPE_FILES: './types.h'
  UTILS_FILES: './utils/**/*.{h,c}'
  LINEAR_SEARCH_FILES: './search/linear-search/linear-search.{h,c} ./search/linear-search/main.c'
  LINEAR_SEARCH_OUTPUT_FILE: './linear-search.o'
  BINARY_SEARCH_FILES: './search/binary-search/binary-search.{h,c} ./search/binary-search/main.c'
  BINARY_SEARCH_OUTPUT_FILE: './binary-search.o'
  BUBBLE_SORT_FILES: './sort/bubble-sort/bubble-sort.{h,c} ./sort/bubble-sort/main.c'
  BUBBLE_SORT_OUTPUT_FILE: './bubble-sort.o'

tasks:
  compile-linear-search:
    cmd: '{{ .COMPILER }} {{ .TYPE_FILES }} {{ .UTILS_FILES }} {{ .LINEAR_SEARCH_FILES }} -o {{ .LINEAR_SEARCH_OUTPUT_FILE }}'

  run-linear-search:
    cmd: '{{ .LINEAR_SEARCH_OUTPUT_FILE }}'

  remove-linear-search-binary-file:
    cmd: 'rm {{ .LINEAR_SEARCH_OUTPUT_FILE }}'

  linear-search:
    cmds:
      - task: compile-linear-search
      - task: run-linear-search
      - task: remove-linear-search-binary-file

  compile-binary-search:
    cmd: '{{ .COMPILER }} -Wall -g {{ .TYPE_FILES }} {{ .UTILS_FILES }} {{ .BINARY_SEARCH_FILES }} -o {{ .BINARY_SEARCH_OUTPUT_FILE }} -lm'

  run-binary-search:
    cmd: '{{ .BINARY_SEARCH_OUTPUT_FILE }}'

  remove-binary-search-binary-file:
    cmd: 'rm {{ .BINARY_SEARCH_OUTPUT_FILE }}'

  binary-search:
    cmds:
      - task: compile-binary-search
      - task: run-binary-search
      - task: remove-binary-search-binary-file

  compile-bubble-sort:
    cmd: '{{ .COMPILER }}  -g {{ .TYPE_FILES }} {{ .UTILS_FILES }} {{ .BUBBLE_SORT_FILES }} -o {{ .BUBBLE_SORT_OUTPUT_FILE }} -lm'

  run-bubble-sort:
    cmd: '{{ .BUBBLE_SORT_OUTPUT_FILE }}'

  remove-bubble-sort-file:
    cmd: 'rm {{ .BUBBLE_SORT_OUTPUT_FILE }}'

  bubble-sort:
    cmds:
      - task: compile-bubble-sort
      - task: run-bubble-sort
      - task: remove-bubble-sort-file